version: '3'
services:
  newscast_services:
    image: creativitykills/nginx-php-server
    container_name: newscast
    ports:
      - "44678:80"
    volumes:
      - ./:/var/www
    networks:
      - backend

  mysql:
    container_name: db_mysql
    image: mysql:5.7
    ports:
      - "33062:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=ajimoti"
    volumes:
      - "./db/mysql/data:/var/lib/mysql"
      - "./db/mysql/initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - backend
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "44679:80"
    environment:
      - "PMA_HOST=db_mysql"
      - "MYSQL_DATABASE=newscast"
      - "MYSQL_ROOT_PASSWORD=ajimoti"
    networks:
      - backend

networks:
  backend:
    driver: bridge
